/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafemanager;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author BlackVernon
 */
public class BillGUI extends javax.swing.JFrame {
    private ArrayList<Bill> billList = new ArrayList<Bill>();
    /**
     * Creates new form BillGUI
     *
     * @return
     */
    

    private void addMoreGUI(){
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        doneBtn_1.setBounds(0,MAXIMIZED_HORIZ,200, 200);
        billText_1.add(doneBtn_1);
        doneBtn_2.setBounds(0,MAXIMIZED_HORIZ,200, 200);
        billText_2.add(doneBtn_2);
        doneBtn_3.setBounds(0,MAXIMIZED_HORIZ,200, 200);
        billText_3.add(doneBtn_3);
        doneBtn_4.setBounds(0,MAXIMIZED_HORIZ,200, 200);
        billText_4.add(doneBtn_4);
    }
    
    public BillGUI() throws SQLException, ClassNotFoundException {
        initComponents();
        addMoreGUI();
        //Get Connection
        String ipAddress="";
        ResultSet result = Connection.Connect(ipAddress,"1433","HoaDon","sa","sa2017");
        while(result.next()){
            Bill tempBill = new Bill();
            tempBill.setIdBill(result.getString("MaHoaDon"));
            billList.add(tempBill);
        }
        
        this.billText_1.setText(billList.get(0).toString());
        this.billText_1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        billText_1 = new javax.swing.JTextPane();
        doneBtn_1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        billText_2 = new javax.swing.JTextPane();
        doneBtn_2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        billText_3 = new javax.swing.JTextPane();
        doneBtn_3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        billText_4 = new javax.swing.JTextPane();
        doneBtn_4 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setViewportView(billText_1);

        getContentPane().add(jScrollPane1);

        doneBtn_1.setText("jButton2");
        getContentPane().add(doneBtn_1);

        jScrollPane2.setViewportView(billText_2);

        getContentPane().add(jScrollPane2);

        doneBtn_2.setText("jButton3");
        getContentPane().add(doneBtn_2);

        jScrollPane3.setViewportView(billText_3);

        getContentPane().add(jScrollPane3);

        doneBtn_3.setText("jButton4");
        getContentPane().add(doneBtn_3);

        jScrollPane4.setViewportView(billText_4);

        getContentPane().add(jScrollPane4);

        doneBtn_4.setText("jButton5");
        getContentPane().add(doneBtn_4);

        setSize(new java.awt.Dimension(703, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new BillGUI().setVisible(true);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(BillGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane billText_1;
    private javax.swing.JTextPane billText_2;
    private javax.swing.JTextPane billText_3;
    private javax.swing.JTextPane billText_4;
    private javax.swing.JButton doneBtn_1;
    private javax.swing.JButton doneBtn_2;
    private javax.swing.JButton doneBtn_3;
    private javax.swing.JButton doneBtn_4;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
