/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafemanager;

import java.awt.Graphics;
import java.awt.Image;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author BlackVernon
 */
public class BillGUI extends javax.swing.JFrame {

    private final ArrayList<Bill> billList = new ArrayList<>();

    /**
     * Creates new form BillGUI
     *
     * @return
     */
    private void addMoreGUI() {
        ImagePanel panel = new ImagePanel(
                new ImageIcon("E:\\Code\\Java\\CafeManager\\Design\\image\\loginBackgroundRaw.jpg").getImage());
        setBounds(0, 0, 1366, 720);
        getContentPane().add(panel);
        setVisible(true);
        billPanel1.setEditable(false);
        billPanel2.setEditable(false);
        billPanel3.setEditable(false);
        doneBtnBillPanel1.setContentAreaFilled(false);
        doneBtnBillPanel2.setContentAreaFilled(false);
        doneBtnBillPanel3.setContentAreaFilled(false);
    }

    public BillGUI() throws SQLException, ClassNotFoundException, Exception {
        initComponents();
        addMoreGUI();
        //Get Connection
        String ipAddress = IPAddress.getIP();
        ResultSet result = Connection.Connect(ipAddress, "1433", "CAFE", "sa", "sa2017");
        while (result.next()) {
            Bill tempBill = new Bill();
            tempBill.setIdBill(result.getString("MaChucVu"));
            billList.add(tempBill);
        }
//        this.billText_1.setText(billList.get(0).toString());
//        this.billText_1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        billPanel3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        billPanel1 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        billPanel2 = new javax.swing.JTextPane();
        doneBtnBillPanel1 = new javax.swing.JButton();
        doneBtnBillPanel2 = new javax.swing.JButton();
        doneBtnBillPanel3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 720));

        jScrollPane3.setViewportView(billPanel3);

        jScrollPane4.setViewportView(billPanel1);

        jScrollPane5.setViewportView(billPanel2);

        doneBtnBillPanel1.setIcon(new javax.swing.ImageIcon("E:\\Code\\Java\\CafeManager\\Design\\image\\loginCheck100px.png")); // NOI18N

        doneBtnBillPanel2.setIcon(new javax.swing.ImageIcon("E:\\Code\\Java\\CafeManager\\Design\\image\\loginCheck100px.png")); // NOI18N

        doneBtnBillPanel3.setIcon(new javax.swing.ImageIcon("E:\\Code\\Java\\CafeManager\\Design\\image\\loginCheck100px.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(doneBtnBillPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(367, 367, 367)
                .addComponent(doneBtnBillPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doneBtnBillPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(doneBtnBillPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doneBtnBillPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doneBtnBillPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1382, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new BillGUI().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(BillGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane billPanel1;
    private javax.swing.JTextPane billPanel2;
    private javax.swing.JTextPane billPanel3;
    private javax.swing.JButton doneBtnBillPanel1;
    private javax.swing.JButton doneBtnBillPanel2;
    private javax.swing.JButton doneBtnBillPanel3;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
