/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafemanager;

import control.Connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ASUS
 */
public final class SuaMon extends javax.swing.JFrame {

    Item mon;
    private final String ipAddress = "192.168.43.88";
    private static String maMon;
    private static String tenMon;
    private static String moTa;
    private static float gia;

    /**
     * Creates new form SuaMon
     * @param maMon
     * @param tenMon
     * @param moTa
     * @param gia
     */
    public SuaMon(String maMon, String tenMon, String moTa, float gia) {
        SuaMon.maMon = maMon;
        SuaMon.tenMon = tenMon;
        SuaMon.moTa = moTa;
        SuaMon.gia = gia;
        initComponents();
        loadData();
    }

    public void loadData() {
        txtMaMon.setText(maMon);
        txtTenMon.setText(tenMon);
        txtMoTa.setText(moTa);
        txtGiaMon.setText(gia + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtMaMon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTenMon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        cboDanhMuc = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtGiaMon = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        btnHuyBo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 600));

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 600));
        jPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Mã món ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 60, 169, 40);

        txtMaMon.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel1.add(txtMaMon);
        txtMaMon.setBounds(210, 60, 260, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tên món ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 140, 169, 40);

        txtTenMon.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel1.add(txtTenMon);
        txtTenMon.setBounds(210, 140, 260, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Mô tả món");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 220, 169, 40);

        txtMoTa.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jScrollPane3.setViewportView(txtMoTa);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(210, 220, 260, 90);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Danh mục món ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 360, 169, 40);

        cboDanhMuc.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        cboDanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đồ uống", "Đồ ăn" }));
        jPanel1.add(cboDanhMuc);
        cboDanhMuc.setBounds(210, 360, 260, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Giá món");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 440, 169, 40);

        txtGiaMon.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel1.add(txtGiaMon);
        txtGiaMon.setBounds(210, 440, 260, 40);

        btnXacNhan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel1.add(btnXacNhan);
        btnXacNhan.setBounds(110, 520, 110, 38);

        btnHuyBo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHuyBo.setText("Hủy bỏ");
        jPanel1.add(btnHuyBo);
        btnHuyBo.setBounds(270, 520, 110, 38);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/QL.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        mon = new Item(txtMaMon.getText(), txtTenMon.getText(), txtMoTa.getText(), cboDanhMuc.getItemAt(cboDanhMuc.getSelectedIndex()), txtGiaMon.getText());
        try {
            java.sql.Connection con;
            con = (Connection) Connect.getConnect(ipAddress);
            String queryString = "update Mon set MaMon =? ,MaDanhMuc =?, TenMon =? ,MoTaMon =? ,AnhMon ='' ,GiaMon = ? where MaMon =" + "'" + maMon + "'";
            PreparedStatement statement = con.prepareStatement(queryString);
            statement.setString(1, mon.getIdItem());
            String danhMuc = mon.getDanhMuc();
            System.out.println(danhMuc);
            switch (danhMuc) {
                case "Ăn sáng":
                    statement.setString(2, "DM_1");
                    break;
                case "Ăn trưa":
                    statement.setString(2, "DM_2");
                    break;
                case "Ăn tối":
                    statement.setString(2, "DM_3");
                    break;
                case "Đồ ngọt":
                    statement.setString(2, "DM_4");
                    break;
                case "Nước":
                    statement.setString(2, "DM_5");
                    break;
            }
            statement.setString(3, mon.getItemName());
            statement.setString(4, mon.getExpressItem());
            statement.setString(5, mon.getPrice());
            statement.executeUpdate();
            con.close();

        } catch (SQLException ex) {
            System.out.println(ex);
        }
        QuanLy quanLy = null;
        try {
            quanLy = new QuanLy();
        } catch (Exception ex) {
            Logger.getLogger(SuaMon.class.getName()).log(Level.SEVERE, null, ex);
        }
        quanLy.loadDataMon();
        quanLy.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SuaMon(maMon, tenMon, moTa, gia).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cboDanhMuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtGiaMon;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextPane txtMoTa;
    private javax.swing.JTextField txtTenMon;
    // End of variables declaration//GEN-END:variables
}
